# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diarium', '0002_auto_20161127_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiariumProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diarium.Notebook')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diarium', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
