# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarium', '0003_diariumprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='character_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
