# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarium', '0005_auto_20161130_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='is_diary',
            field=models.BooleanField(default=False),
        ),
    ]
